### ISSUE TITLE
pack broken

### ISSUE THREAD

**Issue by Anniepoo** [fifth-postulate/julian#8]
4 ?- pack_install(julian).
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
Install julian@0.1.3 from https://github.com/mndrix/julian/archive/v0.1.3.zip Y/n? 
ERROR: v0.1.3.zip: A package archive must be named <pack>-<version>.<ext>
false.

The swi-Prolog server's rather sick tonight, this could just be a side-effect

**Comment by mndrix** [comment]
I think this is actually a bug in the pack infrastructure.  I reported it on the mailing list, but haven't gotten around to submitting a fix.  Until that's done, you should be able to install packs by using the full URL.  For julian, this should work: `pack_install('https://github.com/mndrix/julian/archive/v0.1.3.zip').`

**Comment by Anniepoo** [comment]
What do you wish to do
   (1) \* Install proposed dependencies
   (2)   Only install requested package
   (3)   Cancel

Your choice? 
% "v0.1.3.zip" was downloaded 2 times
ERROR: v0.3.2.zip: A package archive must be named <pack>-<version>.<ext>
false.

looks like it's endemic

**Comment by mndrix** [comment]
That makes sense.  Dependencies call pack_install recursively, so you'd probably have to install those manually too.  I'll try to send Jan a patch as soon as I can.
